package com.firestorm.llwindow

enum class ECursorType {
    UI_CURSOR_ARROW,
    UI_CURSOR_WAIT,
    UI_CURSOR_HAND,
    UI_CURSOR_IBEAM,
    UI_CURSOR_CROSS,
    UI_CURSOR_SIZENWSE,
    UI_CURSOR_SIZENESW,
    UI_CURSOR_SIZEWE,
    UI_CURSOR_SIZENS,
    UI_CURSOR_SIZEALL,
    UI_CURSOR_NO,
    UI_CURSOR_WORKING,
    UI_CURSOR_TOOLGRAB,
    UI_CURSOR_TOOLLAND,
    UI_CURSOR_TOOLFOCUS,
    UI_CURSOR_TOOLCREATE,
    UI_CURSOR_ARROWDRAG,
    UI_CURSOR_ARROWCOPY,
    UI_CURSOR_ARROWDRAGMULTI,
    UI_CURSOR_ARROWCOPYMULTI,
    UI_CURSOR_NOLOCKED,
    UI_CURSOR_ARROWLOCKED,
    UI_CURSOR_GRABLOCKED,
    UI_CURSOR_TOOLTRANSLATE,
    UI_CURSOR_TOOLROTATE,
    UI_CURSOR_TOOLSCALE,
    UI_CURSOR_TOOLCAMERA,
    UI_CURSOR_TOOLPAN,
    UI_CURSOR_TOOLZOOMIN,
    UI_CURSOR_TOOLZOOMOUT,
    UI_CURSOR_TOOLPICKOBJECT3,
    UI_CURSOR_TOOLPLAY,
    UI_CURSOR_TOOLPAUSE,
    UI_CURSOR_TOOLMEDIAOPEN,
    UI_CURSOR_PIPETTE,
    UI_CURSOR_TOOLSIT,
    UI_CURSOR_TOOLBUY,
    UI_CURSOR_TOOLPAY,
    UI_CURSOR_TOOLOPEN,
    UI_CURSOR_TOOLPATHFINDING,
    UI_CURSOR_TOOLPATHFINDING_PATH_START,
    UI_CURSOR_TOOLPATHFINDING_PATH_START_ADD,
    UI_CURSOR_TOOLPATHFINDING_PATH_END,
    UI_CURSOR_TOOLPATHFINDING_PATH_END_ADD,
    UI_CURSOR_TOOLNO;

    companion object {
        fun fromString(cursorString: String): ECursorType {
            return entries.firstOrNull { it.name.equals(cursorString, ignoreCase = true) }
                ?: UI_CURSOR_ARROW
        }
    }
}
