package com.firestorm.llplugin

interface LLPluginClassMediaOwner {

    enum class EMediaEvent {
        MEDIA_EVENT_CONTENT_UPDATED,
        MEDIA_EVENT_TIME_DURATION_UPDATED,
        MEDIA_EVENT_SIZE_CHANGED,
        MEDIA_EVENT_CURSOR_CHANGED,
        MEDIA_EVENT_NAVIGATE_BEGIN,
        MEDIA_EVENT_NAVIGATE_COMPLETE,
        MEDIA_EVENT_PROGRESS_UPDATED,
        MEDIA_EVENT_STATUS_TEXT_CHANGED,
        MEDIA_EVENT_NAME_CHANGED,
        MEDIA_EVENT_LOCATION_CHANGED,
        MEDIA_EVENT_NAVIGATE_ERROR_PAGE,
        MEDIA_EVENT_CLICK_LINK_HREF,
        MEDIA_EVENT_CLICK_LINK_NOFOLLOW,
        MEDIA_EVENT_CLOSE_REQUEST,
        MEDIA_EVENT_PICK_FILE_REQUEST,
        MEDIA_EVENT_GEOMETRY_CHANGE,
        MEDIA_EVENT_PLUGIN_FAILED_LAUNCH,
        MEDIA_EVENT_PLUGIN_FAILED,
        MEDIA_EVENT_AUTH_REQUEST,
        MEDIA_EVENT_FILE_DOWNLOAD,
        MEDIA_EVENT_DEBUG_MESSAGE,
        MEDIA_EVENT_LINK_HOVERED,
    }

    enum class EMediaStatus {
        MEDIA_NONE,
        MEDIA_LOADING,
        MEDIA_LOADED,
        MEDIA_ERROR,
        MEDIA_PLAYING,
        MEDIA_PAUSED,
        MEDIA_DONE,
    }

    fun handleMediaEvent(self: LLPluginClassMedia, event: EMediaEvent) {}
}
